// <auto-generated />
using CollectionsTask.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectionsTask.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20260910131940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankLib.AccountSystem.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<int>("AssociatedID")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("Decimal(19,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AccountNumber");

                    b.HasIndex("AssociatedID");

                    b.ToTable("Accounts", (string)null);

                    b.HasDiscriminator<string>("AccountKind").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankLib.Login.LoginAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("BankLib.AccountSystem.CheckingAccount", b =>
                {
                    b.HasBaseType("BankLib.AccountSystem.Account");

                    b.Property<bool>("IsOverdraftEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("OverdraftLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Decimal(19,2)")
                        .HasDefaultValue(0m);

                    b.HasDiscriminator().HasValue("Checking");
                });

            modelBuilder.Entity("BankLib.AccountSystem.LoanAccount", b =>
                {
                    b.HasBaseType("BankLib.AccountSystem.Account");

                    b.HasDiscriminator().HasValue("Loan");
                });

            modelBuilder.Entity("BankLib.AccountSystem.SavingsAccount", b =>
                {
                    b.HasBaseType("BankLib.AccountSystem.Account");

                    b.HasDiscriminator().HasValue("Savings");
                });

            modelBuilder.Entity("BankLib.AccountSystem.Account", b =>
                {
                    b.HasOne("BankLib.Login.LoginAccount", null)
                        .WithMany()
                        .HasForeignKey("AssociatedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
